CREATE TABLE IF NOT EXISTS harga (
    id SERIAL PRIMARY KEY,
    tanggal DATE NOT NULL,
    harga NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);